name=input("please entre the name ")
print(len(name))
print(name.endswith("noi"))
print(name.endswith("noia"))
print(name.count("s"))
print(name.capitalize())
print(name.find("s"))
print(name.replace("s","t"))
print(name.title())